### ISSUE TITLE
Add interactions for changeset highlighting

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/owlviewer#6]
Would love to be able to do the following:
- Upon hovering over a changeset on the map or in the toolbar, highlight corresponding match.
- On click, center map over changeset
- On click, add persistent 'active' class to changeset in list
- On click, bring changeset in list into view if it is out of view due to sidebar scroll.

**Comment by ppawel** [comment]
I've been thinking how to approach interaction with changesets but still don't have a clear picture. 

What you suggested is good but the main problem is that when you see the changeset list you are at ZL16. This means that (for most changesets) you cannot see the whole changeset. So should "centering map over changeset" change your view so it shows changeset bbox (could even be the whole world for some changesets)?

On the other hand it kind of does not make sense to center the map over the part of changeset that you're currently seeing at ZL16 because you see on the changeset list precisely and only because it is in your view... so centering loses its function here.

**Comment by ppawel** [comment]
Another thing I was thinking about is kind of a changeset "inspector" mode - you select one specific changeset from the list and you can inspect it, e.g. see details of all objects involved, see in detail what's changed (what tags etc).
